### 상품추가
POST http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzY0MjgwLCJleHAiOjE2ODA0NTA2ODB9.10WwvOkaI0zb2aaj27WQDcOLauhhNpYTSIvoFO91chY

{
  "description": "상품설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스"
}

### 상품 아이쳄 추가
POST http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzY0MjgwLCJleHAiOjE2ODA0NTA2ODB9.10WwvOkaI0zb2aaj27WQDcOLauhhNpYTSIvoFO91chY

{
      "productId" : 1,
      "count": 1,
      "name": "280",
      "price": 100000
}


### 이메일 인증(고객)
GET http://localhost:8080/signup/customer/verify/?email=kys1064@naver.com&code=S5tjMrqzeN