### 상품 추가
POST http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDI4MjQ1LCJleHAiOjE2ODA1MTQ2NDV9.84XxPjPV843XbIwAYjlbowSz8_-qSy9AuaUqeUfp9gs

{
  "description": "상품설명",
  "items": [
    {
      "count": 2,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스"
}

### 상품 아이템 추가
POST http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDI4MjQ1LCJleHAiOjE2ODA1MTQ2NDV9.84XxPjPV843XbIwAYjlbowSz8_-qSy9AuaUqeUfp9gs

{
      "productId" : 1,
      "count": 1,
      "name": "280",
      "price": 100000
}


### 상품 수정
PUT http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDI4MjQ1LCJleHAiOjE2ODA1MTQ2NDV9.84XxPjPV843XbIwAYjlbowSz8_-qSy9AuaUqeUfp9gs

{
  "description": "상품설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}

### 상품 아이템 수정
PUT http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDI4MjQ1LCJleHAiOjE2ODA1MTQ2NDV9.84XxPjPV843XbIwAYjlbowSz8_-qSy9AuaUqeUfp9gs

{
  "id": 1,
  "count": 1,
  "name": "260",
  "price": 100000
}


### 상품 삭제
DELETE http://localhost:8081/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDI4MjQ1LCJleHAiOjE2ODA1MTQ2NDV9.84XxPjPV843XbIwAYjlbowSz8_-qSy9AuaUqeUfp9gs

{
  "description": "상품설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}

### 상품 아이템 삭제
DELETE http://localhost:8081/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDI4MjQ1LCJleHAiOjE2ODA1MTQ2NDV9.84XxPjPV843XbIwAYjlbowSz8_-qSy9AuaUqeUfp9gs

### 상품 검색
GET http://localhost:8081/search/product?name=나이키
Content-Type: application/json

### 상품 상세 검색
GET http://localhost:8081/search/product/detail?productId=1
Content-Type: application/json

### 카트 추가
POST http://localhost:8081/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzNTcsImV4cCI6MTY4MDQ0Mjc1N30.EYyStxjtbGSYi-tsi_i7_RUnXazTYVZ3sDbwPztXub4

{
  "description": "상품설명",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스 한정판",
  "sellerId": 1
}

### 카트 조회
GET http://localhost:8081/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzNTcsImV4cCI6MTY4MDQ0Mjc1N30.EYyStxjtbGSYi-tsi_i7_RUnXazTYVZ3sDbwPztXub4

### 카트 주문
POST http://localhost:8081/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTYzNTcsImV4cCI6MTY4MDQ0Mjc1N30.EYyStxjtbGSYi-tsi_i7_RUnXazTYVZ3sDbwPztXub4

{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "sellerId": 1,
      "name": "나이키 에어포스 한정판",
      "description": "상품설명",
      "items": [
        {
          "id": 1,
          "name": "270",
          "count": 1,
          "price": 100000
        }
      ]
    }
  ],
  "messages": []
}